name: Build Latest Document

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/document.yaml'
      - 'mkdocs.yaml'
      - 'poetry.lock'
      - 'docs/**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch origin doc:doc
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ hashFiles('poetry.lock') }}
      - name: "Setup Poetry"
        run: |
          pip install --upgrade pip
          pip install --user poetry
          poetry config virtualenvs.in-project true
      - name: "Build Latest Document"
        run: |
          poetry install
          poetry run mike deploy --push --update-aliases latest
